### ISSUE TITLE
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant

### ISSUE THREAD

**Issue by gebalassa** [IIC2233-2016-02/Syllabus#711]
**¡Saludos!**

Después de tener éxito al momento de realizar la autentificación dentro de una función, decidí separarlo en un módulo aparte y llamar a la función (que retorna el objeto "youtube" obtenido mediante `build`) desde otro módulo. Desde este último, intento utilizar el objeto para crear una playlist, aplicando el comando:
``` 
def crear_playlist(self, nombre):
    playlists_insert_response = self.youtube.playlists().insert(
    part="snippet,status",
    body=dict(
      snippet=dict(
        title=nombre,
        description="Playlist automática llamada {}".format(nombre)
        ),
      status=dict(
        privacyStatus="private"
        )
      )
    ).execute()
   ```
donde `self.youtube` corresponde al objeto obtenido del módulo de autentificación.
Sin embargo, me aparece el siguiente error y las soluciones que he encontrado no funcionan.

```
Traceback (most recent call last):
  File "C:\Users\Gabriel\Desktop\T07_WORKZONE\probando codigo Youtube.py", line 56, in <module>
    programa.crear_playlist("testing 1")
  File "C:\Users\Gabriel\Desktop\T07_WORKZONE\probando codigo Youtube.py", line 42, in crear_playlist
    privacyStatus="private"
  File "C:\Program Files\Python35\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\googleapiclient\http.py", line 833, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Program Files\Python35\lib\site-packages\googleapiclient\http.py", line 160, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\oauth2client\transport.py", line 186, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Program Files\Python35\lib\site-packages\oauth2client\client.py", line 756, in _refresh
    self._do_refresh_request(http)
  File "C:\Program Files\Python35\lib\site-packages\oauth2client\client.py", line 812, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant
```

Para intentar arreglar esto, agregué al "client_secrets.json" un parámetro de la forma `access_type=offline`, que supuestamente se encargaría de manejar el "Token Refresh" o algo así. No cambió nada.
Otra solución que encontré se relacionaba a un tema de expiración producto de tener mala la hora del PC que generaba el "invalid_grant" (que puede tener distintas causas), sin embargo no es mi caso pues acabo de actualizar la hora usando time.windows.com y el problema persiste.

Gracias por la comprensión

**Comment by gebalassa** [comment]
UPDATE: 

Probé directamente el ejemplo de creación de playlist de YT, y luego de la autentificación (que sale bien) me lanza el mismo error.
